[project]
name = "connectomics-at-cosyne"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "caveclient>=8.0.1",
    "jupyter>=1.1.1",
    "lab>=8.8",
]
