project:
  type: website
  output-dir: _site

website:
  title: "Synapses at Scale - COSYNE 2026"
  navbar:
    left:
      - href: workshop.ipynb
        text: Workshop
      - href: https://www.cosyne.org/
        text: COSYNE
    tools: 
      - icon: github
        menu:
          - text: Tutorial Code
            url:  https://github.com/AllenInstitute/connectomics_at_cosyne
  back-to-top-navigation: true
  page-footer: 
      center: "Website built by: Bethanny Danskin. Image credit: Forrest Collman."
      border: false

format:
  html:
    theme: darkly
    toc: false